import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. PrizeProviderをインポート（パスは配置場所に合わせて調整してください）
import { PrizeProvider } from "./PrizeContext"; 
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 2. childrenをPrizeProviderで包む */}
        <PrizeProvider>
          {children}
        </PrizeProvider>
      
        <footer className="fixed bottom-0 left-0 right-0 border-t bg-white shadow-lg z-50">
          <nav className="flex justify-around items-center h-16">
            <Link href="/home" className="flex flex-col items-center text-gray-600 hover:text-blue-500 transition-colors">
              <span className="text-xl">🏠</span>
              <span className="text-xs">ホーム</span>
            </Link>
            <Link href="/settings" className="flex flex-col items-center text-gray-600 hover:text-blue-500 transition-colors">
              <span className="text-xl">⚙️</span>
              <span className="text-xs">設定</span>
            </Link>
          </nav>
          {/* iPhoneなどのホームバー対策（Safe Area） */}
          <div className="h-safe-bottom" />
        </footer>
      </body>
    </html>
  );
}